### PR TITLE
Added the RiderApplicationShowPage

### PR DESCRIPTION
**Pull request by Daoyijiucsb**
In this pull request, I added the RiderApplicationShowPage. Users can click "show" on the Rider Applications Table to view the details of any application on the page, but they cannot edit them.
[my PR link](https://proj-gauchoride-daoyi-dev.dokku-13.cs.ucsb.edu/apply/rider)

The page contains Status, Email, Date Applied,Date Cancelled, Notes, Perm Number, Description

After task 6 is completed, I will modify the page so that the displayed elements vary depending on the status.

image:
Screenshot 2024-02-29 at 18 08 08

[Close#31](https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-1/issues/31)

### CODE REVIEW

**Comment by Ze-el** [comment]
Can you add the deployment link on the PR?

**Comment by Daoyijiucsb** [comment]
I added a link.

**Review by Ze-el — APPROVED** [review]
The code looks good to me and I can see the show page in the driver application.

**Review by liamlizard — APPROVED** [review]
LGTM. Works as expected on deployment.

**Review by Aasish-Virjala — APPROVED** [review]
LGTM

**Pull request merged**
