### PR TITLE
Limit the displayed element in the ShowRiderApplyPage

### LINKED ISSUE #19: Students can apply to use the Gauchoride service, and admins can manage applications : #5 "ApplyRiderPage"
Fifth issue: Rider Pages
- [ ] There are is a page component at the /apply/rider url that meets all of the acceptance criteria.
- [ ]  There is a page component for the /apply/rider/edit/:id url that meets all of the acceptance criteria
- [ ]  All other acceptance criteria from the rider perspective listed above are met

### LINKED ISSUE #32: #5 "ApplyRiderPage"  in RiderApplicaitonshowPage, "Cancelled Date" is only shown when it is cancelled
In the applyRiderShowPage, 
Cancelled, Accepted, Declined Date is displayed only when it is Cancelled, Accepted, Declined. 
Note is displayed if it is not null

### PR DESCRIPTION
**Pull request by Daoyijiucsb**
Limit the displayed element in the ShowRiderApplyPage
[Dev Link](https://proj-gauchoride-daoyi-dev.dokku-13.cs.ucsb.edu/)

In the applyRiderShowPage, 
the Cancelled, Accepted, and Declined Dates are displayed only when the status is Cancelled, Accepted, or Declined respectively. 
The Note is displayed if it is not null.

The status of the application is 'pending'
Screenshot 2024-03-07 at 13 18 23

The status of the application is 'accepted'
Screenshot 2024-03-07 at 13 18 46

close [#32](https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-1/issues/32)
close [#19](https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-1/issues/19)

### CODE REVIEW

**Review by Ze-el — DISMISSED** [review]
LGTM! can you also add Closes #19 along with this as well?

**Review by owenjpark — DISMISSED** [review]
LGTM!

**Review by Ze-el — DISMISSED** [review]
LGTM! The displayed element Is condensed and not all dates are displayed

**Review by jamespflaging — DISMISSED** [review]
LGTM - merge conflicts are fixed!

**Review by jamespflaging — DISMISSED** [review]
LGTM post merge!

**Review by jamespflaging — APPROVED** [review]
LGTM

**Review by andrewpengucsb — APPROVED** [review]
LGTM

**Pull request merged**
