### PR TITLE
James - Add DB record and fixtures for Driver Availability

### LINKED ISSUE #10: Driver Availability #1: Add database record and fixtures
Prerequisite: None, part of #4 

### 1st issue: Database record and fixtures

- [x] There is an `@Entity` called DriverAvailability with fields: `Long id`, (type depends) `driverId`, `String day`, `String startTime`, `String endTime`, `String notes`.
- [x] There is a `@Repository` called `DriverAvailabilityRepository`.
- [x] There is a fixtures file `driverAvailabilityFixtures.js`.

### PR DESCRIPTION
**Pull request by jamespflaging**
In this PR I add the fixtures, repository, and entity files for Driver Availability. I modeled them after existing files in gauchoride and compared them to our code from team03.

Closes #10

### CODE REVIEW

**Review by liamlizard — APPROVED** [review]
LGTM! Code looks good and checks pass.

**Review by Aasish-Virjala — APPROVED** [review]
LGTM

**Review by gretchenlam — CHANGES_REQUESTED** [review]
I noticed that in other fixtures files, they export using `export {Fixtures};`

Could you change `export default driverAvailabilityFixtures;` to  `export {driverAvailabilityFixtures};`?

Or you could follow shiftFixtures.js and do both:
```
export default driverAvailabilityFixtures;
export { driverAvailabilityFixtures };
```

This change will resolve my tests as I am working on driverAvailabilityForm

**Comment by Ze-el** [comment]
Under the file driverAvailabilityFixtures.js, the 2nd id of threeAvailability has the wrong format of startTime.

**Review by Ze-el — APPROVED** [review]
LGTM now!

**Review by gretchenlam — APPROVED** [review]
LGTM!

**Pull request merged**
